server:
  port: 8090
app:
  security:
    jwt:
      secret: homes123
      issuer: IssuerHomes 
      expiration-sec: 120
      clock-skew-sec: 120
  service:
     TokenService: "JwtTokenService" 
     UserService: "InMemoryUserService"
     ConfigurationService: "InMemoryConfigurationService" 
     AuthenticationService: "JwtTokenAuthenticationService"
logging:
  file: /Users/istiaque_hussain/projects/coe/logs/${spring.application.name}.log
  pattern:
    file: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ} [%c] %p %m%n"
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ} [%c] %p %m%n"
  level:
    .: "ERROR"
    org.springframework: INFO
    com.coe.homs: DEBUG